# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe ToDosController, type: :controller do
  before :each do
    request.headers['accept'] = 'application/json'
  end

  # This should return the minimal set of attributes required to create a valid
  # ToDo. As you add validations to ToDo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { garden_id: 1, title: 'test', body: 'test', type: 'SimpleToDo' }
  end

  let(:invalid_attributes) do
    { garden_id: nil, title: nil, body: nil }
  end

  let(:user) do
    User.create!(name: 'test_name', email: 'test_email')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ToDosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'returns a success response' do
      # to_do = ToDo.create! valid_attributes
      get :index, params: { user_id: user.id }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      to_do = user.simple_to_dos.create! valid_attributes
      get :show, params: { user_id: user.id, id: to_do.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new ToDo' do
        expect do
          post :create, params: { user_id: user.id, to_do: valid_attributes }, session: valid_session
        end.to change(SimpleToDo, :count).by(1)
      end

      it 'renders a JSON response with the new to_do' do
        post :create, params: { user_id: user.id, to_do: valid_attributes }, session: valid_session
        expect(response).to have_http_status(:created)
        expect(response.content_type).to eq('application/json')
      end
    end

    context 'with invalid params' do
      it 'renders a JSON response with errors for the new to_do' do
        post :create, params: { user_id: user.id, to_do: invalid_attributes }, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        { garden_id: 2, title: 'test2', body: 'test2' }
      end

      it 'updates the requested to_do' do
        to_do = user.simple_to_dos.create! valid_attributes
        put :update, params: { user_id: user.id, id: to_do.to_param, to_do: new_attributes }, session: valid_session
        to_do.reload
        expect(SimpleToDo.where(title: 'test2').exists?).to be true
      end

      it 'renders a JSON response with the to_do' do
        to_do = user.simple_to_dos.create! valid_attributes

        put :update, params: { user_id: user.id, id: to_do.to_param, to_do: valid_attributes }, session: valid_session
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq('application/json')
      end
    end

    context 'with invalid params' do
      it 'renders a JSON response with errors for the to_do' do
        to_do = user.simple_to_dos.create! valid_attributes

        put :update, params: { user_id: user.id, id: to_do.to_param, to_do: invalid_attributes }, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested to_do' do
      to_do = user.simple_to_dos.create! valid_attributes
      expect do
        delete :destroy, params: { user_id: user.id, id: to_do.to_param }, session: valid_session
      end.to change(user.simple_to_dos.all, :count).by(-1)
    end
  end
end
